server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.217.128
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin
  redis:
    host: 192.168.217.128
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://192.168.217.128:2181
  protocol:
    port: -1
  provider:
    timeout: 10000
