server:
  port: 8083
spring:
  data:
    solr:
      host: http://192.168.217.128:8080/solr
  thymeleaf:
    cache: false
dubbo:
  application:
    name: search
  registry:
    address: zookeeper://192.168.217.128:2181
  consumer:
    check: false